package task_5;

public class FifthView {
        final static String ENTER_VAL="Please, enter a size of the matrix [1-9]:";
        final static String ERROR_VAL="Error, enter a valid value";
        final static String BLINK=" ";
        final static String INITIAL_MATRIX="Initial matrix generated by random values:";
        final static String FINAL_MATRIX="Final matrix reversed on 90 grades:";
        final static String ENTER_TASK="Reversing of the matrix with entered size ";


        public  void showMessage(String mes){
            System.out.println(mes);
        }

        public FifthView(){}

        public void displayArray(int[][]array){
            for(int i=0;i<array.length;i++){
                for(int j=0;j<array.length;j++)
                    System.out.print(array[i][j]);
                System.out.println();
            }
        }

}

